<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PlatformTarget>x64</PlatformTarget>
		<AssemblySearchPaths>
			$(AssemblyPath);
			$(AssemblySearchPaths)
		</AssemblySearchPaths>
		<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="mscorlib"></Reference>
		<Reference Include="System"></Reference>
		<Reference Include="System.Core"></Reference>
		<Reference Include="System.Xml"></Reference>
		<Reference Include="0Harmony"></Reference>
		<Reference Include="Assembly-CSharp"></Reference>
		<Reference Include="Unity.Collections"></Reference>
		<Reference Include="UnityEngine"></Reference>
		<Reference Include="UnityEngine.CoreModule"></Reference>
		<Reference Include="UnityEngine.IMGUIModule"></Reference>
		<Reference Include="UnityEngine.TextRenderingModule"></Reference>
	</ItemGroup>
</Project>

